//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateRegistration
    {
        public long Number { get; set; }
        public int IdPerson { get; set; }
        public string VIN { get; set; }
        public string NumberTransportVehicle { get; set; }
        public Nullable<int> IdDepartment { get; set; }
        public Nullable<System.DateTime> DateReceipt { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual TransportVehicle TransportVehicle { get; set; }
        public virtual User User { get; set; }
    }
}
