//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingLicenceCategory
    {
        public int IdDLC { get; set; }
        public string NumberDrivingLicence { get; set; }
        public int IdCategory { get; set; }
        public System.DateTime DateReseiptCategory { get; set; }
    
        public virtual CategoryTV CategoryTV { get; set; }
        public virtual DriverLicence DriverLicence { get; set; }
    }
}
