//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Penalty()
        {
            this.PenaltyArticle = new HashSet<PenaltyArticle>();
        }
    
        public int IdPenalty { get; set; }
        public string NumberDrivingLicence { get; set; }
        public string Location { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual DriverLicence DriverLicence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PenaltyArticle> PenaltyArticle { get; set; }
    }
}
