//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int IdPenalty { get; set; }
        public string NumberDrivingLicence { get; set; }
        public int IdEmployee { get; set; }
        public string Location { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> IdArticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual DriverLicence DriverLicence { get; set; }
    }
}
