//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyArticle
    {
        public int IdPenaltyArticle { get; set; }
        public int IdPenalty { get; set; }
        public int IdArticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Penalty Penalty { get; set; }
    }
}
