//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportVehicle()
        {
            this.CertificateRegistration = new HashSet<CertificateRegistration>();
        }
    
        public string VIN { get; set; }
        public int IdModel { get; set; }
        public int IdColor { get; set; }
        public int IdCategoryTV { get; set; }
        public Nullable<System.DateTime> YearOfManufacture { get; set; }
    
        public virtual CategoryTV CategoryTV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateRegistration> CertificateRegistration { get; set; }
        public virtual Color Color { get; set; }
        public virtual ModelTV ModelTV { get; set; }
    }
}
