//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDriverLicence
    {
        public string PhotoPath { get; set; }
        public string FIO { get; set; }
        public string NumberDrivingLicence { get; set; }
        public System.DateTime DateReceipt { get; set; }
        public string NameDepartment { get; set; }
        public string Categories { get; set; }
    }
}
