//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPenalty
    {
        public string PhotoPath { get; set; }
        public string FIO { get; set; }
        public Nullable<int> CountPenalty { get; set; }
        public Nullable<decimal> SumPenalty { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> Unpaid { get; set; }
        public string ColorUser { get; set; }
    }
}
