//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPS_GIBDD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransportVehicle
    {
        public string PhotoPath { get; set; }
        public string FIO { get; set; }
        public long Number { get; set; }
        public Nullable<System.DateTime> DateReceipt { get; set; }
        public string VIN { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public int IdBrand { get; set; }
        public string PhotoTVPath { get; set; }
        public string NumberTransportVehicle { get; set; }
    }
}
